# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 17:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='User', max_length=50)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('location', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=250)),
                ('user_type', models.CharField(choices=[('1', 'Designer'), ('2', 'Developer'), ('3', 'Both')], default='1', max_length=10)),
                ('website', models.URLField(blank=True, max_length=100)),
                ('about', models.TextField(default='about', max_length=500)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('dribbble', models.CharField(blank=True, max_length=50)),
                ('github', models.CharField(blank=True, max_length=50)),
                ('user_level', models.CharField(default='user', max_length=9)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
