# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(default='Points', max_length=75)),
                ('point_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_score',
            field=models.IntegerField(default=10),
        ),
    ]
