# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-08 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180307_2338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoreValues',
        ),
    ]
