# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-09 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_scorevalues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_level',
        ),
    ]
