# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-10 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_userpost_post_body_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='post_body',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='post_body_test',
        ),
    ]
