# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-10 01:12
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20180310_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='post_body',
            field=ckeditor.fields.RichTextField(default='Text'),
        ),
    ]
