# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0002_userpost_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toUser', models.CharField(default='user', max_length=6)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notify_type', models.CharField(max_length=6)),
                ('read', models.BooleanField(default=False)),
                ('fromUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='feed.UserPost')),
            ],
        ),
    ]
